# Generated by Django 5.1.1 on 2024-09-05 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Очки')),
                ('first_login', models.DateTimeField(blank=True, null=True, verbose_name='Первый вход')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boost_type', models.CharField(choices=[('speed', 'Ускорение'), ('strength', 'Сила'), ('defense', 'Защита')], max_length=20, verbose_name='Тип буста')),
                ('duration', models.DurationField(verbose_name='Длительность буста')),
                ('activated_at', models.DateTimeField(auto_now_add=True, verbose_name='Время активации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='task_1.player')),
            ],
        ),
    ]
